spring:
  datasource:
    url: jdbc:mariadb://42.193.96.38:3306/pysch
    username: pysch
    password: pysch001
    driver-class-name: org.mariadb.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml